CREATE TABLE belt_promotions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT                   NOT NULL REFERENCES users (id),
    gym_id              BIGINT                   REFERENCES gyms (id),
    belt_rank_id        BIGINT                   NOT NULL REFERENCES belt_ranks (id),
    stripes             INT                      NOT NULL DEFAULT 0,
    promoted_by_user_id BIGINT                   REFERENCES users (id),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_belt_promotions_user ON belt_promotions (user_id, created_at);
