-- Reservas reutilizam class_attendances.status ('PRESENT' | 'RESERVED')

CREATE TABLE gym_products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id      BIGINT                   NOT NULL REFERENCES gyms (id),
    name        VARCHAR(120)             NOT NULL,
    description VARCHAR(500),
    price_cents INT                      NOT NULL,
    image_key   VARCHAR(300),
    link        VARCHAR(300),
    active      BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_products_gym ON gym_products (gym_id, active);

CREATE TABLE gym_orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT                   NOT NULL REFERENCES gym_products (id),
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_orders_product ON gym_orders (product_id);

ALTER TABLE gyms ADD COLUMN logo_key VARCHAR(300);
ALTER TABLE gyms ADD COLUMN phone VARCHAR(30);
ALTER TABLE gyms ADD COLUMN email VARCHAR(255);
ALTER TABLE gyms ADD COLUMN website VARCHAR(255);
ALTER TABLE gyms ADD COLUMN address VARCHAR(255);

CREATE TABLE gym_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id      BIGINT                   NOT NULL REFERENCES gyms (id),
    storage_key VARCHAR(300)             NOT NULL,
    position    INT                      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_photos_gym ON gym_photos (gym_id, position);
