CREATE TABLE gym_reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id     BIGINT                   NOT NULL REFERENCES gyms (id),
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    rating     INTEGER                  NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gym_reviews_gym_user UNIQUE (gym_id, user_id)
);

CREATE INDEX idx_gym_reviews_gym ON gym_reviews (gym_id);
