CREATE TABLE gym_verifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id        BIGINT                   NOT NULL REFERENCES gyms (id),
    status        VARCHAR(20)              NOT NULL,
    cnpj          VARCHAR(14)              NOT NULL,
    ai_confidence DOUBLE PRECISION,
    ai_summary    VARCHAR(2000),
    ai_raw        VARCHAR(8000),
    review_notes  VARCHAR(1000),
    reviewed_by   BIGINT REFERENCES users (id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gym_verifications_gym UNIQUE (gym_id)
);

CREATE TABLE gym_verification_media (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_id BIGINT       NOT NULL REFERENCES gym_verifications (id),
    storage_key     VARCHAR(300) NOT NULL,
    kind            VARCHAR(20)  NOT NULL,
    position        INTEGER      NOT NULL DEFAULT 0
);

CREATE INDEX idx_gym_verification_media_v ON gym_verification_media (verification_id);
