CREATE TABLE user_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    gym_id      BIGINT REFERENCES gyms (id),
    type        VARCHAR(30)              NOT NULL,
    event_value INTEGER,
    detail      VARCHAR(200),
    belt_slug   VARCHAR(40),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_user_events_user ON user_events (user_id, occurred_at DESC);
CREATE INDEX idx_user_events_gym ON user_events (gym_id, occurred_at DESC);
