ALTER TABLE users ADD COLUMN pro BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN avatar_key VARCHAR(300);
ALTER TABLE users ADD COLUMN bio VARCHAR(500);
ALTER TABLE users ADD COLUMN certificate_key VARCHAR(300);

CREATE TABLE user_medals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    competition VARCHAR(100)             NOT NULL,
    tier        VARCHAR(20)              NOT NULL,
    medal_count INTEGER                  NOT NULL DEFAULT 1,
    position    INTEGER                  NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_user_medals_user ON user_medals (user_id);

CREATE TABLE user_follows (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT                   NOT NULL REFERENCES users (id),
    following_id BIGINT                   NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_user_follows UNIQUE (follower_id, following_id)
);

CREATE INDEX idx_user_follows_following ON user_follows (following_id);
