ALTER TABLE users ADD COLUMN accent_color VARCHAR(9);

CREATE TABLE user_photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    storage_key VARCHAR(300)             NOT NULL,
    position    INTEGER                  NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_user_photos_user ON user_photos (user_id);
