-- Social interactions on public training sessions shown in the Comunidade feed:
-- likes, comments, and a share counter (mirrors the gym Mural posts).
CREATE TABLE check_in_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id BIGINT                   NOT NULL REFERENCES check_ins (id),
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_check_in_like UNIQUE (check_in_id, user_id)
);

CREATE TABLE check_in_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id BIGINT                   NOT NULL REFERENCES check_ins (id),
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    content     VARCHAR(1000)            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_check_in_likes ON check_in_likes (check_in_id);
CREATE INDEX idx_check_in_comments ON check_in_comments (check_in_id);

ALTER TABLE check_ins ADD COLUMN share_count INTEGER NOT NULL DEFAULT 0;
