-- Private per-gym notes an instructor keeps on a student (injuries, focus,
-- behaviour). Scoped to a gym so the same person seen by two gyms has separate
-- notes.
CREATE TABLE gym_student_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id          BIGINT                   NOT NULL REFERENCES gyms (id),
    student_user_id BIGINT                   NOT NULL REFERENCES users (id),
    author_user_id  BIGINT                   NOT NULL REFERENCES users (id),
    content         VARCHAR(2000)            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_student_notes ON gym_student_notes (gym_id, student_user_id, created_at);
