-- Account settings: a private account is hidden from the global Comunidade feed
-- and people-search; notification preferences are stored for when push lands.
ALTER TABLE users ADD COLUMN private_account   BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN notify_community  BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN notify_messages   BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN notify_promotions BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    message    VARCHAR(2000)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
