-- Technique library (Técnicas): a curated catalog browsable by category, user
-- favorites, and private personal techniques with external video links.
-- Hosting curated videos is deferred, so curated entries are text references for now.

CREATE TABLE techniques (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(80)  NOT NULL,
    category       VARCHAR(20)  NOT NULL, -- GUARD, PASSING, SUBMISSION, SWEEP, ESCAPE, TAKEDOWN, CONTROL
    name_pt        VARCHAR(120) NOT NULL,
    position_pt    VARCHAR(120),
    description_pt VARCHAR(1000),
    difficulty     VARCHAR(20)  NOT NULL, -- FUNDAMENTAL, INTERMEDIATE, ADVANCED
    belt_slug      VARCHAR(40),           -- suggested belt (string, not FK)
    video_url      VARCHAR(500),          -- external link (nullable; hosting deferred)
    sort_order     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uq_techniques_slug UNIQUE (slug)
);

CREATE INDEX idx_techniques_category ON techniques (category, sort_order);

CREATE TABLE technique_favorites (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES users (id),
    technique_id BIGINT                   NOT NULL REFERENCES techniques (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_technique_favorites UNIQUE (user_id, technique_id)
);

CREATE TABLE personal_techniques (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    name       VARCHAR(120)             NOT NULL,
    category   VARCHAR(20),
    notes      VARCHAR(1000),
    video_url  VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_personal_techniques_user ON personal_techniques (user_id, created_at);

-- Seed: fundamental BJJ techniques across categories (pt-BR)
INSERT INTO techniques (slug, category, name_pt, position_pt, description_pt, difficulty, belt_slug, sort_order) VALUES
 ('armlock-guarda-fechada', 'SUBMISSION', 'Armlock da guarda fechada', 'Guarda fechada', 'Chave de braço clássica a partir da guarda fechada: quebre a postura, suba o quadril e isole o braço para hiperestender o cotovelo.', 'FUNDAMENTAL', 'adult-white', 10),
 ('triangulo', 'SUBMISSION', 'Triângulo', 'Guarda fechada', 'Estrangulamento com as pernas, prendendo um braço e a cabeça do oponente entre as coxas.', 'FUNDAMENTAL', 'adult-white', 20),
 ('mata-leao', 'SUBMISSION', 'Mata-leão', 'Pegada das costas', 'Estrangulamento por trás com o antebraço sobre o pescoço; finalização das costas com os ganchos.', 'FUNDAMENTAL', 'adult-white', 30),
 ('kimura', 'SUBMISSION', 'Kimura', 'Meia-guarda / guarda', 'Chave de ombro com pegada dupla (figura quatro) no punho e cotovelo do oponente.', 'FUNDAMENTAL', 'adult-blue', 40),
 ('omoplata', 'SUBMISSION', 'Omoplata', 'Guarda aberta / borboleta', 'Chave de ombro aplicada com as pernas; também usada como raspagem e controle de transição.', 'INTERMEDIATE', 'adult-blue', 50),
 ('passagem-em-pe', 'PASSING', 'Passagem de guarda em pé', 'Dentro da guarda fechada', 'Abra a guarda fechada ficando de pé e controle os quadris para iniciar a passagem.', 'FUNDAMENTAL', 'adult-white', 60),
 ('passagem-toreando', 'PASSING', 'Passagem toreando (matador)', 'Guarda aberta', 'Passagem dinâmica controlando as canelas e contornando as pernas como num passe de toureiro.', 'INTERMEDIATE', 'adult-blue', 70),
 ('passagem-knee-cut', 'PASSING', 'Passagem joelho no meio (knee cut)', 'Guarda aberta', 'Corte a guarda com o joelho atravessando a coxa do oponente, conectando ombro e pressão.', 'INTERMEDIATE', 'adult-blue', 80),
 ('raspagem-tesoura', 'SWEEP', 'Raspagem de tesoura', 'Guarda fechada', 'Raspagem clássica usando as pernas em tesoura para inverter a posição e cair por cima.', 'FUNDAMENTAL', 'adult-white', 90),
 ('raspagem-meia-guarda', 'SWEEP', 'Raspagem da meia-guarda', 'Meia-guarda profunda', 'Use o gancho e a underhook para levantar e inverter o oponente a partir da meia-guarda.', 'INTERMEDIATE', 'adult-blue', 100),
 ('berimbolo', 'SWEEP', 'Berimbolo', 'Guarda De La Riva', 'Inversão moderna a partir da De La Riva para girar por baixo e chegar às costas.', 'ADVANCED', 'adult-purple', 110),
 ('upa', 'ESCAPE', 'Upa (saída da montada)', 'Montada (por baixo)', 'Saída fundamental da montada: prenda braço e perna do mesmo lado e gire em ponte.', 'FUNDAMENTAL', 'adult-white', 120),
 ('fuga-de-quadril', 'ESCAPE', 'Fuga de quadril (shrimp)', 'Cem quilos / montada', 'Movimento base para criar espaço com o quadril e recompor a guarda.', 'FUNDAMENTAL', 'adult-white', 130),
 ('puxada-para-guarda', 'TAKEDOWN', 'Puxada para guarda', 'Em pé', 'Sente puxando o oponente para dentro da guarda com controle de gola e manga.', 'FUNDAMENTAL', 'adult-white', 140),
 ('queda-single-leg', 'TAKEDOWN', 'Queda single leg', 'Em pé', 'Agarre uma das pernas do oponente e leve-o ao solo mantendo a cabeça do lado de dentro.', 'INTERMEDIATE', 'adult-blue', 150),
 ('controle-cem-quilos', 'CONTROL', 'Cem quilos (controle lateral)', 'Cento e vinte / lateral', 'Controle lateral pressionando o peito do oponente; base para finalizações e transições.', 'FUNDAMENTAL', 'adult-white', 160);
