-- Multi-factor auth (TOTP authenticator app). The secret is stored once enrolled;
-- mfa_enabled flips true only after the user confirms a valid code. Recovery codes
-- are single-use, stored hashed.
ALTER TABLE users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN totp_secret VARCHAR(64);

CREATE TABLE mfa_recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    code_hash  VARCHAR(100)             NOT NULL,
    used       BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_mfa_recovery_user ON mfa_recovery_codes (user_id);
