-- Wearable integration scaffold. Cloud providers (WHOOP/Garmin/Oura) connect via
-- OAuth and the backend pulls samples; Apple Health is on-device and the app pushes
-- samples to /users/me/biometrics. Biometric samples unlock the locked metric tiles.
CREATE TABLE wearable_connections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                   NOT NULL REFERENCES users (id),
    provider      VARCHAR(20)              NOT NULL, -- WHOOP, GARMIN, OURA, APPLE_HEALTH
    status        VARCHAR(20)              NOT NULL, -- CONNECTED, DISCONNECTED, PENDING
    external_id   VARCHAR(120),
    access_token  VARCHAR(500),                      -- placeholder for real OAuth tokens (encrypt later)
    refresh_token VARCHAR(500),
    connected_at  TIMESTAMP WITH TIME ZONE,
    last_sync_at  TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_wearable_conn UNIQUE (user_id, provider)
);

CREATE TABLE biometric_samples (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES users (id),
    provider     VARCHAR(20)              NOT NULL,
    metric       VARCHAR(30)              NOT NULL, -- RECOVERY, READINESS, SLEEP, HRV, RESTING_HR, VO2MAX, RECOVERY_TIME
    sample_date  DATE                     NOT NULL,
    metric_value DOUBLE PRECISION         NOT NULL, -- "value" is reserved -> metric_value
    unit         VARCHAR(20),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_biometric_sample UNIQUE (user_id, metric, sample_date)
);

CREATE INDEX idx_biometric_user_metric ON biometric_samples (user_id, metric, sample_date);
