-- Push notifications. Device tokens are captured for later remote delivery (Expo
-- push needs a dev/EAS build + APNs/FCM keys); notification records back an in-app
-- notification center now and respect the user's notify_* preferences.
CREATE TABLE push_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    token      VARCHAR(255)             NOT NULL,
    platform   VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_push_token UNIQUE (token)
);

CREATE INDEX idx_push_tokens_user ON push_tokens (user_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    type       VARCHAR(30)              NOT NULL, -- COMMUNITY, MESSAGE, PROMOTION, SYSTEM
    title      VARCHAR(150)             NOT NULL,
    body       VARCHAR(500),
    payload    VARCHAR(500),                       -- optional deep-link payload
    is_read    BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notifications_user ON notifications (user_id, created_at);
