-- Body pain / injury map. Athletes log pain per body region (0-10) from a workout
-- report or standalone; the latest entry per region within a recent window drives
-- the body-map heat coloring. Logging intensity 0 clears a region.
CREATE TABLE pain_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    region      VARCHAR(30)              NOT NULL,
    intensity   INTEGER                  NOT NULL, -- 0-10
    note        VARCHAR(300),
    check_in_id BIGINT REFERENCES check_ins (id),
    occurred_at DATE                     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pain_logs_user ON pain_logs (user_id, region, occurred_at);
