-- A dated pain "assessment": a full snapshot of where it hurts (multiple areas,
-- each with a type + intensity) plus context (onset, trend, frequency, what
-- relieves/worsens, notes), so a pain issue can be tracked over time. Separate
-- from the lightweight per-region pain_logs used inside check-ins.
CREATE TABLE pain_assessments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id),
    assessed_on DATE                     NOT NULL,
    onset_date  DATE,
    trend       VARCHAR(10),                                  -- BETTER | SAME | WORSE
    frequency   VARCHAR(20),                                  -- CONSTANT | INTERMITTENT | ON_MOVEMENT | AT_REST | MORNING | NIGHT
    relieves    VARCHAR(500),
    worsens     VARCHAR(500),
    notes       VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_pain_assessments_user ON pain_assessments (user_id, assessed_on DESC);

CREATE TABLE pain_assessment_areas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT      NOT NULL REFERENCES pain_assessments (id),
    region        VARCHAR(40) NOT NULL,
    pain_type     VARCHAR(20),                                -- STAB | PRESSURE | BURNING | THROBBING | TINGLING | HEAVY | OTHER
    intensity     INTEGER     NOT NULL,
    note          VARCHAR(300)
);
CREATE INDEX idx_paa_assessment ON pain_assessment_areas (assessment_id);
CREATE INDEX idx_paa_region ON pain_assessment_areas (region);
