ALTER TABLE users ADD COLUMN current_streak INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN longest_streak INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_check_in_date DATE;
ALTER TABLE users ADD COLUMN weekly_goal INT NOT NULL DEFAULT 3;
ALTER TABLE users ADD COLUMN city VARCHAR(100);

CREATE TABLE check_ins (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT                   NOT NULL REFERENCES users (id),
    check_date       DATE                     NOT NULL,
    session_type     VARCHAR(20),
    duration_minutes INT,
    notes            VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_check_ins_user_date ON check_ins (user_id, check_date);

CREATE TABLE gyms (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(150)             NOT NULL,
    city       VARCHAR(100)             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE gym_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id    BIGINT                   NOT NULL REFERENCES gyms (id),
    user_id   BIGINT                   NOT NULL REFERENCES users (id),
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gym_members UNIQUE (gym_id, user_id)
);

-- Seed inicial de academias (sugestões por cidade até o Phase 2 trazer geolocalização)
INSERT INTO gyms (name, city, created_at)
VALUES ('Gracie Barra Centro', 'São Paulo', CURRENT_TIMESTAMP),
       ('Alliance Tatuapé', 'São Paulo', CURRENT_TIMESTAMP),
       ('Checkmat Vila Mariana', 'São Paulo', CURRENT_TIMESTAMP),
       ('GFTeam Copacabana', 'Rio de Janeiro', CURRENT_TIMESTAMP),
       ('Nova União Tijuca', 'Rio de Janeiro', CURRENT_TIMESTAMP),
       ('Atos BH Savassi', 'Belo Horizonte', CURRENT_TIMESTAMP),
       ('CT Leão Curitiba', 'Curitiba', CURRENT_TIMESTAMP),
       ('Soul Fighters Floripa', 'Florianópolis', CURRENT_TIMESTAMP);
