-- One-time codes for "forgot password". Each request stores a hashed 6-digit code
-- with a short expiry; reset verifies the latest unused, non-expired one.
CREATE TABLE password_reset_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    code_hash  VARCHAR(100)             NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used       BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_password_reset_user ON password_reset_tokens (user_id, created_at DESC);
