-- Links a user to a third-party identity (Google/Apple). One row per provider
-- identity; (provider, subject) is globally unique. Enables social sign-in/linking.
CREATE TABLE oauth_accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    provider   VARCHAR(20)              NOT NULL,   -- GOOGLE | APPLE
    subject    VARCHAR(255)             NOT NULL,   -- provider's stable user id ("sub")
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_oauth_provider_subject UNIQUE (provider, subject)
);
CREATE INDEX idx_oauth_user ON oauth_accounts (user_id);
