CREATE TABLE gym_post_media (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT                   NOT NULL REFERENCES gym_posts (id),
    storage_key VARCHAR(300)             NOT NULL,
    media_type  VARCHAR(10)              NOT NULL,
    position    INT                      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_post_media_post ON gym_post_media (post_id, position);
