CREATE TABLE gym_post_saves (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT                   NOT NULL REFERENCES gym_posts (id),
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gym_post_saves UNIQUE (post_id, user_id)
);

CREATE INDEX idx_gym_post_saves_user ON gym_post_saves (user_id, created_at);
