CREATE TABLE gym_classes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id             BIGINT                   NOT NULL REFERENCES gyms (id),
    name               VARCHAR(100)             NOT NULL,
    instructor_user_id BIGINT                   REFERENCES users (id),
    day_of_week        INT                      NOT NULL,
    start_time         TIME                     NOT NULL,
    end_time           TIME                     NOT NULL,
    session_type       VARCHAR(15)              NOT NULL,
    restriction_mode   VARCHAR(10)              NOT NULL DEFAULT 'ALL',
    allowed_belt_slugs VARCHAR(300),
    active             BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_classes_gym ON gym_classes (gym_id, day_of_week, start_time);

CREATE TABLE class_attendances (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_class_id      BIGINT                   NOT NULL REFERENCES gym_classes (id),
    class_date        DATE                     NOT NULL,
    user_id           BIGINT                   NOT NULL REFERENCES users (id),
    status            VARCHAR(10)              NOT NULL DEFAULT 'PRESENT',
    marked_by_user_id BIGINT                   REFERENCES users (id),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_class_attendance UNIQUE (gym_class_id, class_date, user_id)
);

CREATE INDEX idx_class_att_occurrence ON class_attendances (gym_class_id, class_date);
CREATE INDEX idx_class_att_user ON class_attendances (user_id, class_date);
