CREATE TABLE gym_medals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id      BIGINT                   NOT NULL REFERENCES gyms (id),
    competition VARCHAR(100)             NOT NULL,
    tier        VARCHAR(20)              NOT NULL,
    medal_count INTEGER                  NOT NULL DEFAULT 1,
    position    INTEGER                  NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_medals_gym ON gym_medals (gym_id);
