CREATE TABLE submission_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL REFERENCES users (id),
    check_in_id  BIGINT REFERENCES check_ins (id),
    submission   VARCHAR(40)              NOT NULL,
    direction    VARCHAR(10)              NOT NULL,
    qty          INTEGER                  NOT NULL DEFAULT 1,
    occurred_at  DATE                     NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_submission_logs_user ON submission_logs (user_id, direction, occurred_at);
