CREATE TABLE belt_systems (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE belt_ranks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    belt_system_id BIGINT      NOT NULL REFERENCES belt_systems (id),
    slug           VARCHAR(50) NOT NULL UNIQUE,
    name           VARCHAR(50) NOT NULL,
    name_pt        VARCHAR(50) NOT NULL,
    color_hex      VARCHAR(7)  NOT NULL,
    sort_order     INT         NOT NULL,
    max_stripes    INT         NOT NULL DEFAULT 4
);

INSERT INTO belt_systems (name)
VALUES ('IBJJF Adult'),
       ('IBJJF Kids');

INSERT INTO belt_ranks (belt_system_id, slug, name, name_pt, color_hex, sort_order, max_stripes)
VALUES ((SELECT id FROM belt_systems WHERE name = 'IBJJF Adult'), 'adult-white', 'White', 'Branca', '#FFFFFF', 1, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Adult'), 'adult-blue', 'Blue', 'Azul', '#1D4ED8', 2, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Adult'), 'adult-purple', 'Purple', 'Roxa', '#7C3AED', 3, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Adult'), 'adult-brown', 'Brown', 'Marrom', '#78350F', 4, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Adult'), 'adult-black', 'Black', 'Preta', '#18181B', 5, 6),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Kids'), 'kids-white', 'White', 'Branca', '#FFFFFF', 1, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Kids'), 'kids-grey', 'Grey', 'Cinza', '#9CA3AF', 2, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Kids'), 'kids-yellow', 'Yellow', 'Amarela', '#FACC15', 3, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Kids'), 'kids-orange', 'Orange', 'Laranja', '#F97316', 4, 4),
       ((SELECT id FROM belt_systems WHERE name = 'IBJJF Kids'), 'kids-green', 'Green', 'Verde', '#16A34A', 5, 4);
