-- 1:1 direct messages (Instagram-style Direct). A conversation stores its two
-- participants in canonical order (user_a_id < user_b_id) so a pair maps to one
-- row; per-user last_read timestamps drive unread counts.
CREATE TABLE conversations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id           BIGINT                   NOT NULL REFERENCES users (id),
    user_b_id           BIGINT                   NOT NULL REFERENCES users (id),
    user_a_last_read_at TIMESTAMP WITH TIME ZONE,
    user_b_last_read_at TIMESTAMP WITH TIME ZONE,
    last_message_at     TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_conversation_pair UNIQUE (user_a_id, user_b_id)
);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT                   NOT NULL REFERENCES conversations (id),
    sender_id       BIGINT                   NOT NULL REFERENCES users (id),
    content         VARCHAR(2000)            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);
CREATE INDEX idx_conversations_a ON conversations (user_a_id);
CREATE INDEX idx_conversations_b ON conversations (user_b_id);
