CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)             NOT NULL UNIQUE,
    password_hash VARCHAR(100)             NOT NULL,
    display_name  VARCHAR(100)             NOT NULL,
    age           INT,
    weight_kg     NUMERIC(5, 2),
    height_cm     INT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE user_belt_progress (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT                   NOT NULL UNIQUE REFERENCES users (id),
    belt_rank_id BIGINT                   NOT NULL REFERENCES belt_ranks (id),
    stripes      INT                      NOT NULL DEFAULT 0,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
