CREATE TABLE gym_posts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id         BIGINT                   NOT NULL REFERENCES gyms (id),
    author_user_id BIGINT                   NOT NULL REFERENCES users (id),
    content        VARCHAR(2000)            NOT NULL,
    is_pinned      BOOLEAN                  NOT NULL DEFAULT FALSE,
    share_count    INT                      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_posts_feed ON gym_posts (gym_id, is_pinned, created_at);

CREATE TABLE gym_post_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT                   NOT NULL REFERENCES gym_posts (id),
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gym_post_likes UNIQUE (post_id, user_id)
);

CREATE TABLE gym_post_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT                   NOT NULL REFERENCES gym_posts (id),
    user_id    BIGINT                   NOT NULL REFERENCES users (id),
    content    VARCHAR(1000)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gym_post_comments_post ON gym_post_comments (post_id, created_at);
